<?php

namespace Initium\LaravelTranslatable\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Schema;

class TranslatableCacheCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'translatable:cache';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Cache the translatable column list from the database';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $tables = $this->getTranslationTables();

        if (empty($tables)) {
            $this->warn('No translation tables found (*_translations).');

            return self::SUCCESS;
        }

        $cache = [];

        foreach ($tables as $table) {
            $columns = Schema::getColumnListing($table);

            // Filter out system columns from config
            $exclude = config('translatable.system_columns', ['id', 'locale', 'created_at', 'updated_at']);

            // Filter out foreign key (product_id, category_id, etc.)
            $foreignKey = str($table)->before('_translations')->toString().'_id';
            $exclude[] = $foreignKey;

            $translatableColumns = array_values(array_diff($columns, $exclude));
            $cache[$table] = $translatableColumns;

            $this->line("  <info>{$table}</info>: ".implode(', ', $translatableColumns));
        }

        $content = "<?php\n\n// Generated by: php artisan translatable:cache\n// Time: ".now()->toDateTimeString()."\n\nreturn ".var_export($cache, true).";\n";

        $cachePath = $this->getCachePath();

        // Ensure directory exists
        $directory = dirname($cachePath);
        if (! is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        file_put_contents($cachePath, $content);

        $this->newLine();
        $this->info('Translatable cache created successfully!');
        $this->line("  File: {$cachePath}");

        return self::SUCCESS;
    }

    /**
     * Get all translation tables from the database.
     *
     * @return array<string>
     */
    protected function getTranslationTables(): array
    {
        $tables = Schema::getTables();
        $suffix = config('translatable.table_suffix', '_translations');
        $translationTables = [];

        foreach ($tables as $table) {
            $tableName = $table['name'];
            if (str_ends_with($tableName, $suffix)) {
                $translationTables[] = $tableName;
            }
        }

        return $translationTables;
    }

    /**
     * Get the cache file path from config.
     */
    protected function getCachePath(): string
    {
        $configPath = config('translatable.cache_path', 'bootstrap/cache/translatable.php');

        // Handle relative paths
        if (! str_starts_with($configPath, '/') && ! preg_match('/^[a-zA-Z]:/', $configPath)) {
            return base_path($configPath);
        }

        return $configPath;
    }
}
